# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ac92b64c1c708cd6ab0080d167dfff719a2f982d82b6996e365f0da55e94abcbd472da13cc0b31e16921a487d076699cea7dd2a88f0872ce284ec1d6fc9ff01

test:
  secret_key_base: 1daff64bc790b1151ec8ba712d25e70f7b507366c9eca235d4e9c110ad822b220f2fe42a8be9e1f575b6ea89eed8c3861854bba68e8528b5743e152c92935606

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
